- package:
  - name: aphrograph
  - section:
    - name: exe:aphrograph
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
  - section:
    - name: library
    - message:
      - name: Redundant build-depends entry
      - depends:
        - base-noprelude
  - section:
    - name: test:aphrograph-test
    - message:
      - name: Redundant build-depends entry
      - depends: base-noprelude
