library:
  source-dirs: src

tests:
  unit-test:
    source-dirs: test/unit
    main: Spec.hs
    ghc-options: -Wno-orphans
    dependencies:
    - aphrograph
    - hspec
    - QuickCheck
    - quickcheck-arbitrary-adt
    - random
    - quickcheck-instances

  end2end-test:
    source-dirs: test/end2end
    main: FullSpec.hs
    dependencies:
    - aphrograph
    - hspec
    - warp
    - servant-server
    - http-client
    - http-types
    - servant-mock
    - QuickCheck
    - quickcheck-instances
    - unix
    - async

ghc-options: -Wall -Wno-type-defaults -Werror -j4 -threaded -O2
dependencies:
- aeson
- array
- base-noprelude >= 4.12.0.0
- brick
- comonad
- containers
- Decimal
- exceptions
- fmt >= 0.6.1.1
- hourglass
- http-api-data
- interpolate
- lens
- lens-aeson
- logging-effect
- mmorph
- monad-control
- monad-loops
- mtl
- optparse-simple
- prettyprinter
- relude
- req
- scientific
- text
- time
- transformers
- transformers-base
- vector
- vty

default-extensions:
- RecordWildCards
- OverloadedStrings

name: aphrograph
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md

executables:
  aphrograph:
    source-dirs: app
    main: Main.hs
    dependencies:
    - aphrograph
