library:
  source-dirs: src
tests:
  aphrograph-test:
    source-dirs: test
    main: Spec.hs
    ghc-options: -Wno-orphans
    dependencies:
      - aphrograph
      - hspec
      - QuickCheck
      - quickcheck-arbitrary-adt
      - random
      - quickcheck-instances
      - quickcheck-transformer

ghc-options: -Wall -Wno-type-defaults -Werror -j4 +RTS -A32m -RTS -fno-print-expanded-synonyms
dependencies:
  - aeson
  - array
  - base-noprelude >= 4.12.0.0
  - brick
  - comonad
  - containers
  - Decimal
  - exceptions
  - fmt >= 0.6.1.1
  - hourglass
  - http-api-data
  - http-client
  - interpolate
  - lens
  - lens-aeson
  - logging-effect
  - mmorph
  - monad-control
  - monad-loops
  - mtl
  - optparse-simple
  - prettyprinter
  - relude
  - req
  - scientific
  - singletons
  - text
  - time
  - transformers
  - transformers-base
  - vector
  - vty
default-extensions:
  - RecordWildCards
  - LambdaCase
  - OverloadedStrings
name: aphrograph
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
executables:
  aphrograph:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - aphrograph
