# global dependencies
dependencies:
  - transformers-base
  - monad-control

  - name: relude 
    mixin: (Relude as Prelude)

  - name: base
    mixin: 
      - hiding (Prelude)

ghc-options:
  -Werror -Wall -fexcess-precision -funfolding-use-threshold=16 -fwrite-ide-info -fwarn-unused-binds -fwarn-unused-imports -hiedir=.hie -O2

library:
  source-dirs: ./src
  dependencies:
    - aeson
    - array
    - brick
    - containers
    - Decimal
    - generic-data
    - http-api-data
    - http-client
    - lens
    - lifted-base
    - mtl
    - mmorph
    - retry
    - monad-logger
    - optparse-simple
    - formatting
    - req
    - text
    - time
    - transformers
    - vector
    - modern-uri
    - vty

tests:
  aphrograph-test:
    source-dirs: ./test
    main: Spec.hs
    dependencies:
      - req
      - hourglass
      - Decimal
      - vty
      - http-client
      - aeson
      - containers
      - time
      - mtl
      - formatting
      - lens
      - brick
      - aphrograph
      - hspec
      - QuickCheck
      - quickcheck-arbitrary-adt
      - random
      - quickcheck-instances
      - quickcheck-transformer

default-extensions:
  - RecordWildCards
  - LambdaCase
  - OverloadedStrings
  - MultiParamTypeClasses
  - StrictData

name: aphrograph
version: 0.1.0.0
extra-source-files:
  - README.md

executables:
  aphrograph:
    source-dirs: ./app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - aphrograph
      - vty
      - brick
