library:
  source-dirs: ./src
  dependencies:
    - base-noprelude
    - aeson
    - array
    - brick
    - containers
    - Decimal
    - data-has
    - generic-data
    - http-api-data
    - http-client
    - lens
    - lifted-base
    - mtl
    - monad-control
    - mmorph
    - monad-logger
    - transformers-base
    - optparse-simple
    - formatting
    - relude
    - req
    - text
    - time
    - transformers
    - vector
    - modern-uri
    - vty

tests:
  aphrograph-test:
    source-dirs: ./test
    main: Spec.hs
    dependencies:
      - base-noprelude
      - relude
      - req
      - hourglass
      - Decimal
      - vty
      - http-client
      - aeson
      - containers
      - time
      - mtl
      - formatting
      - lens
      - brick
      - aphrograph
      - hspec
      - QuickCheck
      - quickcheck-arbitrary-adt
      - random
      - quickcheck-instances
      - quickcheck-transformer
      - logging-effect

default-extensions:
  - RecordWildCards
  - LambdaCase
  - OverloadedStrings
  - MultiParamTypeClasses

name: aphrograph
version: 0.1.0.0
extra-source-files:
  - README.md

executables:
  aphrograph:
    source-dirs: ./app
    main: Main.hs
    dependencies:
      - base-noprelude
      - aphrograph
      - vty
      - brick
      - prettyprinter
      - logging-effect
