library:
  source-dirs: ./src
  dependencies:
    - aeson
    - array
    - base-noprelude >= 4.12.0.0
    - brick
    - containers
    - Decimal
    - fmt >= 0.6.1.1
    - http-api-data
    - http-client
    - lens
    - logging-effect
    - mtl
    - optparse-simple
    - relude
    - req
    - text
    - time
    - transformers
    - vector
    - vty

tests:
  aphrograph-test:
    source-dirs: ./test
    main: Spec.hs
    dependencies:
      - base-noprelude >= 4.12.0.0
      - relude
      - req
      - hourglass
      - Decimal
      - vty
      - http-client
      - aeson
      - containers
      - time
      - mtl
      - lens
      - brick
      - fmt
      - aphrograph
      - hspec
      - QuickCheck
      - quickcheck-arbitrary-adt
      - random
      - quickcheck-instances
      - quickcheck-transformer
      - logging-effect

default-extensions:
  - RecordWildCards
  - LambdaCase
  - OverloadedStrings
  - MultiParamTypeClasses

name: aphrograph
version: 0.1.0.0
extra-source-files:
  - README.md

executables:
  aphrograph:
    source-dirs: ./app
    main: Main.hs
    dependencies:
      - aphrograph
      - base-noprelude >= 4.12.0.0
      - vty
      - brick
      - prettyprinter
      - logging-effect
