library:
  source-dirs:
  - src/
  - src/brick

tests:
  aphrograph-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aphrograph
    - hspec
    - QuickCheck
    - random

default-extensions:
- RecordWildCards
- OverloadedStrings

ghc-options:
- -Wall
- -Werror

dependencies:
- base-noprelude
- containers
- text
- comonad
- scientific
- transformers
- fmt
- relude
- array
- brick
- vty
- wreq
- aeson
- lens-aeson
- lens
- hourglass
- logging-effect
- prettyprinter
- interpolate
- monad-loops
- monad-control
- exceptions
- Decimal

name: aphrograph
version: 0.1.0.0

extra-source-files:
- README.md
- ChangeLog.md

author: Author name here
github: githubuser/aphrograph
license: BSD3

executables:
  aphrograph-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aphrograph

description: Please see the README on GitHub at <https://github.com/githubuser/aphrograph#readme>
