library:
  source-dirs: src

tests:
  aphrograph-test:
    source-dirs: test
    main: Spec.hs
    ghc-options: -Wno-orphans

    dependencies:
      - aphrograph
      - hspec
      - QuickCheck
      - quickcheck-arbitrary-adt
      - random

ghc-options: -Wall -Wno-type-defaults -Werror

default-extensions:
  - RecordWildCards
  - OverloadedStrings

dependencies:
  - aeson
  - array
  - base-noprelude >= 4.12.0.0
  - brick
  - comonad
  - containers
  - Decimal
  - exceptions
  - fmt >= 0.6.1.1
  - hourglass
  - interpolate
  - lens
  - lens-aeson
  - logging-effect
  - mmorph
  - monad-control
  - monad-loops
  - mtl
  - optparse-simple
  - prettyprinter
  - relude
  - scientific
  - text
  - transformers
  - transformers-base
  - vty
  - wreq

name: aphrograph
version: 0.1.0.0

extra-source-files:
  - README.md
  - ChangeLog.md

executables:
  aphrograph:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - aphrograph
