library:
  source-dirs:
  - src/
  - src/brick
  default-extensions:
  - RecordWildCards
tests:
  aphrograph-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aphrograph
    - hspec
    - QuickCheck
    - random
    default-extensions:
    - RecordWildCards

ghc-options:
- -Wall
- -Werror

dependencies:
- base >= 4.7 && < 5
- containers
- array
- brick
- vty
- wreq
- aeson
- lens-aeson
- lens
- mtl
- transformers
- sorted-list
- transformers-base
- bytestring
- vector
- hourglass
- logging-effect
- prettyprinter
- text
- interpolate
- monad-loops
- monad-control
- exceptions
- Decimal
name: aphrograph
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/aphrograph
license: BSD3
executables:
  aphrograph-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aphrograph
description: Please see the README on GitHub at <https://github.com/githubuser/aphrograph#readme>
