flags: {}
packages:
  - .
extra-deps: []
resolver: lts-14.16

ghc-options:
  {
    "$locals": -ddump-to-file -ddump-hi,
    "$targets": -Wall -Wno-type-defaults -j4 -fno-print-expanded-synonyms,
    "$everything": -O2 -threaded,
  }
