{ roots = [ "^Main.main$"
          , "^Paths_aphrograph.*$" -- autogenerated so we can't remove unused methods
          , "^Events.*$"
          , "^State.*$"
          , "^Spec.main$"
          , "^.*Spec.spec$"
          ]
, type-class-roots = True
}